### ISSUE TITLE
Install dependencies on import

### ISSUE THREAD

**Issue by MaxWeise** [uci-ml-repo/ucimlrepo#10]
## Current Situation
When using `pip install ucimlrepo` and trying to interact with the dataset, the following libraries needed to be manually installed:
- pandas
- certifi

## How it should be
When calling `pip install ucimlrepo` the dependencies should be installed with the repo. 

## How to fix
List the dependencies in the `pyproject.toml` file. Ideally, fix the installed version, so updates in the libraries don't break the behaviour of the repo.``

**Comment by ptruong0** [comment]
Thanks, it's been fixed

**Comment by TienNguyenMSBA** [comment]
Thank you very much! This helps a ton as I try using ucimlrepo for my projects

**Comment by ngp-2020** [comment]
Mas ensayos, a ver si esto funciona
