### ISSUE TITLE
Wine Quality dataset(s) import problems

### ISSUE THREAD

**Issue by zarkoivkovicc** [uci-ml-repo/ucimlrepo#5]
This might be a stupid question, but the Wine Quality dataset (id=186) is supposed to have two datasets. You can manually download both of them, but when you fetch them using this python package, only white wine dataset is fetched. Am I missing something obvious or this is a bug/feature?

**Comment by ptruong0** [comment]
Ah I see, how would you prefer this issue to be resolved? We could either combine the data for both red and white wine into one dataset when importing the dataset in Python, or split it into two datasets based on wine type (two different dataset pages on the website)?

**Comment by zarkoivkovicc** [comment]
In my opinion, the fetch command could return dictionary, where the keys are 'red' and 'white' and values are the corresponding datasets.

**Comment by ptruong0** [comment]
The Python package should always return an object with the same structure no matter the dataset. It would be confusing for just one dataset to stray from the standard format. In other words, it would not be good practice to implement edge cases for certain datasets.

**Comment by ptruong0** [comment]
I think a good solution would be to combine them into one data table and add an additional column for "red" or "white". Then you can choose to use them together or easily separate them using pandas. e.g. `df.loc[df['color'] == 'red']`

**Comment by zarkoivkovicc** [comment]
For me it doesn't matter, it's either that or having two separate datasets that can be fetched separately.
