### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by sahmerdandx** [uci-ml-repo/ucimlrepo#6]
I think your web site's SSL certificate expired.

**Comment by Wizard254** [comment]
It's taken too long for the SSL certificate to be updated. Disabling SSL certificate verification should `dirtily` fix this, as shown below:
```python
from ucimlrepo import fetch_ucirepo
import ssl

# Ignore ssl certificate verification
ssl._create_default_https_context = ssl._create_unverified_context

# fetch dataset 
covertype = fetch_ucirepo(id=31)
```

**Comment by ptruong0** [comment]
Apologies for the downtime, there was a delay with the university in renewing our SSL certificate.

**Comment by appymittal** [comment]
Just to bring this to your attention, I am still facing the same issue. But @Wizard254  solution worked for me. Thank you!
